---
format: html
editor: source
toc: false
---

# Antecedentes {#antedecents}

Durante los últimos años, el mundo académico ha experimentado una serie de desafíos relacionados con el concepto de apertura, que pueden describirse en dos aspectos principales. El primero se refiere a la llamada crisis de replicación (Baker, 2016; Nosek et al., 2015; Peng, 2015), referida a las dificultades para replicar los resultados de la investigación debido a la falta de transparencia en el proceso de investigación, donde se ha sido posible evidenciar importantes variaciones en los resultados en equipos de investigación con datos idénticos (Breznau et al., 2021). Esto ha tenido como consecuencia no sólo el fracaso en la replicación de muchos hallazgos publicados, sino también el descubrimiento y la denuncia de datos y resultados falsos (Chopik et al., 2018) con el fin de lograr publicar en  revistas de alto impacto. El segundo desafío proviene de la apertura en términos de acceso, mediante el cual varias comunidades académicas han reaccionado contra las altas barreras de pago y el modelo de negocio impuesto por las compañías editoriales para acceder a los productos de la investigación científica: las universidades pagan una suscripción para acceder al trabajo incluso de sus propios investigadores, y a su vez el público fuera de la academia debe pagar nuevamente por obtener productos financiados por sus impuestos. Una de las reacciones más comentadas ha sido la cancelación de las suscripciones a revistas como Elsevier por parte de grandes universidades como UCLA, lo cual posteriormente se resolvió a través de un acuerdo basado en la adopción y promoción de prácticas en Open Access.

Las barreras en la transparencia y el acceso son síntomas de una cultura académica presionada por la publicación de indicadores que están sesgados hacia resultados "significativos" en términos estadísticos, lo que lleva a una tendencia a forzar los resultados (p-hacking), llegando incluso a manipular y falsear datos para confirmar las hipótesis propuestas (Head et al., 2015) o también el establecer hipótesis ad-hoc luego de conocer los resultados de un estudio (Hollenbeck & Wright, 2017; Kerr, 1998). Esto tiene como consecuencia que finalmente el principal público objetivo de la ciencia son los editores de revistas de alto rango, dejando de lado a otros públicos como la sociedad civil, el estado y la ciudadanía. Tal escenario es particularmente sensible para las ciencias sociales, que se supone basan sus estudios en problemas sociales relevantes para las personas, las comunidades y las sociedades en general.

Un número creciente de iniciativas en todo el mundo están abordando temas de replicabilidad, transparencia y acceso en la ciencia, como el Centro para la Ciencia Abierta (COS), la Iniciativa de Berkeley para la Transparencia en Ciencias Sociales (BITSS) y el proyecto Teaching Integrity in Empirical Research (TIER). Estas iniciativas fomentan la apertura en diferentes etapas del proceso de investigación, como la transparencia de los diseños de investigación a través de prerregistros de estudios, la reproducibilidad de los análisis y la manipulación de datos, así como en la publicación de preimpresiones libres de barreras de pago. Muchas de estas prácticas han sido adoptadas por revistas como recomendaciones o incluso requisitos para su publicación, así como promovidas por instituciones científicas gubernamentales. Todo esto implica un gran cambio en la forma de concebir, hacer y enseñar ciencia. Además, parece un paso necesario para hacer que la ciencia sea más relevante y cercana a quienes están fuera de la academia. En otras palabras, sería difícil mejorar la apertura y el intercambio con las comunidades locales si el trabajo dentro de la academia es mayormente cerrado y no colaborativo.

Como muchos otros desarrollos en la ciencia, el movimiento de la ciencia abierta ha llegado lentamente a América Latina, particularmente en las ciencias sociales. Aunque ha habido algunas iniciativas en los últimos años (como el Congreso de Ciencia Abierta y Ciudadanía en Argentina 2018, OpenCon LatAm Colombia 2019), la mayoría de ellas son promovidas desde las ciencias naturales. En esta línea, a partir del año 2021 la Agencia Nacional de Investigación y Desarrollo (ANID) realizará la implementación de una Política de acceso abierto de información científica y datos de investigación, la cual busca establecer un estándar de acceso público a los productos de investigación que hayan sido financiados por recursos de ANID, por lo tanto es de carácter estratégico desarrollar iniciativas que se propongan contribuir a la apertura de la ciencia.

A partir de este diagnóstico, el presente proyecto tiene por objetivo analizar el conocimiento, creencias y prácticas de ciencia abierta en académic_s de ciencias sociales en Chile, y desde este análisis generar recomendaciones y propuestas tanto para el quehacer académico como a las políticas científicas.