---
format: html
editor: visual
---

# Ética {#etica}

## Aprobación comité ético

El estudio “Meritocracia en la escuela: Fundamentos morales del mercado educativo y sus implicancias para la formación ciudadana en Chile”, correspondiente al FONDECYT N° 1210847, cuenta con aprobación ética del Comité de Ética de la Investigación.

El proyecto fue revisado en conformidad con las normativas éticas y los lineamientos establecidos para investigaciones que involucran a seres humanos, y se considera que cumple con los principios éticos fundamentales para la protección, respeto y dignidad de los participantes. En este sentido, se ha garantizado que el proyecto cuente con mecanismos adecuados de consentimiento informado y protección de datos. 

El comité ha aprobado el protocolo con fecha 28 de mayo de 2021 y se autoriza su ejecución conforme a los términos establecidos en el proyecto original. 

## Consentimientos informados

Los participantes del proyecto firmaron un Consentimiento Informado por escrito, en el que se detallan los objetivos del estudio, en qué consiste su participación, qué se hará y cómo se resguardará la información y los datos entregados. Dicho Consentimiento Informado fue firmado el 2021.
