project:
  type: book
  output-dir: docs

book:
  title: "SOGEDI Survey Methodological Manual"
  reader-mode: true
  page-footer:
    left: |
      Project "Socioeconomic and Gender Disparities: A Multi-Country Study (SOGEDI)"
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  cover-image: images/logo-sogedi.png
  favicon: images/logo-sogedi.png
  repo-url: https://sogedi-project.github.io/sogedi-data/
  repo-branch: main
  chapters:
    - index.qmd
    - 01-sample-desing.qmd
    - 02-survey-processing.qmd
    - 03-database.qmd
    - 04-etichs.qmd
    - 05-codebook.qmd
    - 06-questionnaires.qmd
    - 07-technical-sheet.qmd
    - 08-publications.qmd
    
  search:
    location: sidebar
    type: textbox
  sidebar:
    search: true
    style: docked
    pinned: false


format:
  html:
    theme:
      - cosmo
      - sogedi.scss
    code-link: true

editor: visual
lang: en

bibliography: "input/bib/sogedi-data.bib"
csl: "input/bib/apa6.csl"

